MULLIKEN and LOEWDIN POPULATION ANALYSIS 

  atom#    atom      Mulliken charge       Loewdin charge
      1      Na                0.78                  0.67 
      2      Na                0.78                  0.67 
      3      Na                0.78                  0.67 
      4      Na                0.78                  0.67 
      5      Cl               -0.78                 -0.67 
      6      Cl               -0.78                 -0.67 
      7      Cl               -0.78                 -0.67 
      8      Cl               -0.78                 -0.67 

          total                0.00                  0.00 
