Loewdin Charges of the LCFO basis

 molecule#         molecule      Loewdin charge
         1             NaCl                0.00
         2              Na2                1.34
         3               Na                0.67
         4               Cl               -0.67
         5               Cl               -0.67
         6               Cl               -0.67

                      total                0.00
