Loewdin gross orbital population 

   mol#     mol  basisfunction     Loewdin GP
                                   for spin 1
      1    NaCl            1a1           2.00
                            1e           2.00
                            2e           2.00
                           2a1           1.89
                           3a1           1.96
                            3e           1.93
                            4e           1.93
                           4a1           0.28
                         total          14.00

      2     Na2           1a1u           2.00
                          1e1g           2.00
                          2e1g           2.00
                          1e1u           2.00
                          2e1u           2.00
                          1a1g           2.00
                          2a1g           0.37
                          2a1u           0.28
                         total          12.66

      3      Na             3s           0.33
                          2p_y           2.00
                          2p_z           2.00
                          2p_x           2.00
                         total           6.33

      4      Cl             3s           1.87
                          3p_y           1.93
                          3p_z           1.93
                          3p_x           1.93
                         total           7.67

      5      Cl             3s           1.87
                          3p_y           1.93
                          3p_z           1.93
                          3p_x           1.93
                         total           7.67

      6      Cl             3s           1.87
                          3p_y           1.93
                          3p_z           1.93
                          3p_x           1.93
                         total           7.67
