Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Na          -6.93           -5.93 
      2      Na          -6.93           -5.93 
      3      Na          -6.93           -5.93 
      4      Na          -6.93           -5.93 
      5      Cl           6.93            5.93 
      6      Cl           6.93            5.93 
      7      Cl           6.93            5.93 
      8      Cl           6.93            5.93 

Madelung Energy (eV)    -21.73          -15.94 
