#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=premium
#SBATCH --time=04:00:00
#SBATCH --account=jcesr
#SBATCH --job-name=fragment_75
#SBATCH --output=fragment_75-%j.out
#SBATCH --error=fragment_75-%j.error

module load qchem
cd /global/u2/s/sblau/block_2018-08-23-17-39-12-141126/launcher_2018-08-24-19-58-10-170106
rlaunch -c /global/homes/s/sblau/config_edison singleshot --fw_id 3553

# CommonAdapter (SLURM) completed writing Template
