#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=premium
#SBATCH --time=04:00:00
#SBATCH --partition=regular
#SBATCH --account=jcesr
#SBATCH --job-name=FW_job
#SBATCH --output=FW_job-%j.out
#SBATCH --error=FW_job-%j.error
#SBATCH --constraint=haswell

module load qchem/5.1
cd /global/cscratch1/sd/sblau/ion_placement/block_2018-11-13-02-29-26-951243/launcher_2018-11-14-02-46-59-353432
rlaunch -c /global/homes/s/sblau/config singleshot

# CommonAdapter (SLURM) completed writing Template
