#!/usr/bin/env python

"""
This module implements error handlers for QChem runs. Currently tested only
for B3LYP DFT jobs.
"""

from __future__ import division
import copy
from pymatgen.io.qchemio import QcOutput, QcBatchInput
from pymatgen.serializers.json_coders import MSONable
from custodian.custodian import ErrorHandler

__author__ = "Xiaohui Qu"
__version__ = "0.1"
__maintainer__ = "Xiaohui Qu"
__email__ = "xhqu1981@gmail.com"
__status__ = "Alpha"
__date__ = "12/04/13"

class QChemErrorHandler(ErrorHandler, MSONable):
    """
    Error handler for QChem Jobs. Currently tested only for B3LYP DFT jobs
    generated by pymatgen.
    """
    def __init__(self, input_file, output_file):
        """
        Args:
            input_file:
                Name of the QChem input file.
            output_file:
                Name of the QChem output file.
        """
        self.input_file = input_file
        self.output_file = output_file

    def check(self):
        # Checks output file for errors.
        self.outdata = QcOutput(self.output_file).data
        self.qcinp = QcBatchInput.from_file(self.input_file)
        self.error_step_id = None
        self.erros = None
        self.fix_inp = None
        for i, od in self.outdata:
            if od["has_error"]:
                self.error_step_id = i
                self.fix_step = self.qcinp.jobs[i]
                self.errors = od["errors"]
                return True
        return False

