Mulliken and Loewdin gross orbital population 

  atom#    atom   basisfunction     Mulliken GP      Loewdin GP
      1      Li             1s            2.07            1.99
                            2s            0.22            0.30
                         total            2.29            2.29

      2       F             2s            1.93            1.88
                          2p_y            1.93            1.94
                          2p_z            1.93            1.94
                          2p_x            1.93            1.94
                         total            7.71            7.71

