#!/usr/bin/env python
# Copyright (c) Materials Virtual Lab.
# Distributed under the terms of the BSD License.

from __future__ import division, unicode_literals, print_function

import argparse

import sys
from monty.serialization import loadfn

from custodian.custodian import Custodian
import logging


example_yaml = """jobs:
- jb: custodian.vasp.jobs.VaspJob
  params:
    final: False
    suffix: .relax1
- jb: custodian.vasp.jobs.VaspJob
  params:
    final: True
    suffix: .relax2
    settings_override:
    - {"file": "CONTCAR", "action": {"_file_copy": {"dest": "POSCAR"}}}
jobs_common_params:
  vasp_cmd: ["vasp5.4.1"] # Note that vasp cmd is specified as a list. Change this to whatever you use, e.g., with mpirun.
handlers:
- hdlr: custodian.vasp.handlers.VaspErrorHandler
- hdlr: custodian.vasp.handlers.AliasingErrorHandler
- hdlr: custodian.vasp.handlers.MeshSymmetryErrorHandler
validators:
- vldr: custodian.vasp.validators.VasprunXMLValidator
custodian_params:
  scratch_dir: /tmp
"""


def run(args):
    FORMAT = '%(asctime)s %(message)s'
    logging.basicConfig(format=FORMAT, level=logging.INFO, filename="run.log")
    logging.info("Spec file is %s" % args.spec_file)
    d = loadfn(args.spec_file)
    c = Custodian.from_spec(d)
    c.run()

def print_example(args):
    print(example_yaml)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="""
    crun_spec is a convenient script to run custodian style jobs using a
    simple YAML spec.""", epilog="""Author: Shyue Ping Ong""")

    subparsers = parser.add_subparsers()

    prun = subparsers.add_parser("run", help="Run custodian.")
    prun.add_argument("spec_file", metavar="spec_file", type=str,
                      required=True,
                      help="YAML/JSON spec file.")
    prun.set_defaults(func=run)

    prun = subparsers.add_parser(
        "example", help="Print examples. Right now, there is only one example for VASP double relaxation.")
    prun.set_defaults(func=print_example)

    args = parser.parse_args()

    try:
        a = getattr(args, "func")
    except AttributeError:
        parser.print_help()
        sys.exit(0)
    args.func(args)

