title: custodian
email: ongsp@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  Custodian is a simple, robust and flexible just-in-time (JIT) job management
  framework written in Python.
# twitter_username: custodian
github_username: materialsproject

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

favicon_ico: /assets/favicon.ico

aux_links:
  GitHub: [https://github.com/materialsproject/custodian]
  Issues: [https://github.com/materialsproject/custodian/issues]
  Discourse: [https://matsci.org/custodian]
  Materials Project: [https://materialsproject.org]
