#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --qos=condo_blau
#SBATCH --time=240:00:00
#SBATCH --partition=lr6
#SBATCH --account=lr_blau
#SBATCH --job-name=co2_may
#SBATCH --output=co2_may-%j.out
#SBATCH --error=co2_may-%j.error
#SBATCH --constraint=lr6_m192,lr6_cas


module load qchem/5.4.2 && source activate py38
cd /global/home/groups/lr_mp/smblau/co2_capture/block_2022-04-05-23-25-36-079149/launcher_2022-05-28-07-09-52-283190
rlaunch -l ${FW_CONFIG_FILE%/*}/my_launchpad.yaml -w ${FW_CONFIG_FILE%/*}/my_fworker.yaml singleshot

# CommonAdapter (SLURM) completed writing Template
