name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install OpenBabel
      shell: bash -l {0}
      run: conda install -c conda-forge openbabel

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-ci.txt
        pip install .
    - name: pytest
      shell: bash -l {0}
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
      run: |
        pytest custodian --color=yes
