name: Testing

on:
  push:
    branches: [master]
    paths-ignore: [docs/**]
  pull_request:
    branches: [master]
    paths-ignore: [docs/**]

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade pymatgen
          pip install -e '.[dev]'

      - name: pytest
        env:
          PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
          MPLBACKEND: "Agg"
        run: pytest --cov=. --color=yes

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
