name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    # run test.yml first to ensure that the test suite is passing
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: release
        run: |
          pip install build twine
          python -m build
          twine upload --skip-existing dist/*.tar.gz
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
